// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPM2WAQSkS07us7IpMvmFao5JBotAfHU',
    appId: '1:833031792575:web:ea1b17019f8a705cafe30a',
    messagingSenderId: '833031792575',
    projectId: 'chaty-c82a9',
    authDomain: 'chaty-c82a9.firebaseapp.com',
    storageBucket: 'chaty-c82a9.appspot.com',
    measurementId: 'G-1XFKJBGY16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1vXAYEgwZQ_vsQM-HesYCB8HWWIOQYY',
    appId: '1:833031792575:android:1ec967b68eb6380fafe30a',
    messagingSenderId: '833031792575',
    projectId: 'chaty-c82a9',
    storageBucket: 'chaty-c82a9.appspot.com',
  );
}
